feat: add plugins to manual relations
xima-media/xima-typo3-manual pull request #28
Opened 2024-03-26 09:00 UTC by jackd248

Solves #25

2024-03-26 13:12 UTC, jackd248 commented
You're right, but I didn't get the idea behind this. Where can I find the feature to link manual content elements with relations?

2024-03-26 14:00 UTC, maikschneider commented
You can link single `mtext` elements: Just like pages there is a tab for relation setting. I think this is useful when a manual page contains plenty of elements and the related one is at the very bottom.

2024-03-26 14:57 UTC, jackd248 commented
Alright, I will complete the missing stuff.

2024-03-28 13:52 UTC, maikschneider requested changes
Nice. Just some small adjustments

2024-03-28 13:52 UTC, maikschneider commented on Classes/UserFunctions/SelectItemsProcFunc.php
> +    public static function getPlugins(): array
All class members (not invoke) can be protected. Could you please adjust?

2024-03-28 13:52 UTC, maikschneider commented on Classes/EventListener/ModifyButtonBarEventListener.php
> +    protected function getRecords(string $sql, string $table): array
The name is misleading. Could you please change it into something like executeSql, fetchRecords,..

2024-03-28 15:55 UTC, merged

2024-03-28 15:56 UTC, maikschneider commented
@jackd248 appreciate your input, thank you very much!

2024-03-28 16:31 UTC, jackd248 commented
Enjoy your holidays!